# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "task-${version}";
  version = "2.0.1";
  rev = "v${version}";
  goPackagePath = "github.com/go-task/task";
  subPackages = ["cmd/task"];

  src = fetchgit {
    inherit rev;
    url = "https://github.com/go-task/task";
    sha256 = "0pavk8w1aha6x6yzbi69bflhjr8bfia9hjalvaidyqjdf4r1k7mm";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = with stdenv.lib; {
    description = "A task runner / simpler Make alternative written in Go";
    homepage    = "https://github.com/go-task/task";
    license     = licenses.mit;
    platforms   = platforms.all;
    maintainers = with maintainers; [ ysndr ];
  };
}
